### ISSUE TITLE
[Bug] Apk Not Installing, Shows Corrupted

### ISSUE THREAD

**Issue by George-Seven** [Xposed-Modules-Repo/com.yifeplayte.wavecharge#1]
Release: WaveCharge_1.1_sign.apk

Error: Cannot install, shows error

`"There was a problem while parsing the package."`

**Comment by YifePlayte** [comment]
Can't reproduce this bug, please try the latest one.
And also, this module is only compatible with Android 11 and above.

**Comment by George-Seven** [comment]
I see, it must be because I'm on A10. Thanks for info.
